# Generated by Django 3.1.2 on 2021-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20210615_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='percentage',
            field=models.FloatField(max_length=4),
        ),
    ]
